SET IDENTITY_INSERT [dbo].[TB_MAS_LOOKUP] ON 
GO
INSERT [dbo].[TB_MAS_LOOKUP] ([LOOKUP_ID], [LOOKUP_GROUP], [LOOKUP_NAME], [LOOKUP_CODE]) VALUES (1, N'CSV', N'approved', N'A')
GO
INSERT [dbo].[TB_MAS_LOOKUP] ([LOOKUP_ID], [LOOKUP_GROUP], [LOOKUP_NAME], [LOOKUP_CODE]) VALUES (2, N'CSV', N'failed', N'R')
GO
INSERT [dbo].[TB_MAS_LOOKUP] ([LOOKUP_ID], [LOOKUP_GROUP], [LOOKUP_NAME], [LOOKUP_CODE]) VALUES (3, N'CSV', N'finished', N'D')
GO
INSERT [dbo].[TB_MAS_LOOKUP] ([LOOKUP_ID], [LOOKUP_GROUP], [LOOKUP_NAME], [LOOKUP_CODE]) VALUES (4, N'XML', N'approved', N'A')
GO
INSERT [dbo].[TB_MAS_LOOKUP] ([LOOKUP_ID], [LOOKUP_GROUP], [LOOKUP_NAME], [LOOKUP_CODE]) VALUES (5, N'XML', N'rejected', N'R')
GO
INSERT [dbo].[TB_MAS_LOOKUP] ([LOOKUP_ID], [LOOKUP_GROUP], [LOOKUP_NAME], [LOOKUP_CODE]) VALUES (6, N'XML', N'done', N'D')
GO
SET IDENTITY_INSERT [dbo].[TB_MAS_LOOKUP] OFF
GO
